using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// SO for Secrets. Name of SO is the name of the secret, eg. "Paid to Murder"
/// Secrets are generated by the Player and learned by other Actors (Actors don't have secrets themselves)
/// </summary>
[CreateAssetMenu(menuName = "Actor / Secret")]
public class Secret : ScriptableObject
{
    public string descriptor;
    public GlobalSide side;


    [HideInInspector] public int secretID;         //dynamically assigned by DataManager.cs on import

}
